name = "edgeone-random-images"
main = "worker.js"
compatibility_date = "2025-09-28"

[vars]
# no runtime vars here

[kv_namespaces]
  # Provide your namespace id and binding name here
  # Example:
  # { binding = "wj", id = "your-namespace-id" }